export enum PlayerDataProps {
    RANK = "rank",
    KILLS = "kills",
    DEATHS = "deaths",
    STATUS = "status",
    PING = "ping",
    NAME = "name",
    ID = "id",
    NAMECOLOR = "nameColor",
    ISLOGGED = "isLogged",
    PLAY_AS_GUEST = "playAsGuest",
    PED = "ped",
    SAVED_ON_EVENTS = "savedOnEvents",
    ON_EVENT = "onEvent",
}
