export enum PlayerDataProps {
    RANK = "rank",
    RANK_NAME = "rankName",
    ITEMS = "items",
    KILLS = "kills",
    DEATHS = "deaths",
    STATUS = "status",
    PING = "ping",
    NAME = "name",
    ID = "id",
    NAMECOLOR = "nameColor",
    ISLOGGED = "isLogged",
    PLAY_AS_GUEST = "playAsGuest",
    SAVED_ON_EVENTS = "savedOnEvents",
    ON_EVENT = "onEvent",
    ON_ARENA = "onArena",
    DATABASE_ID = "databaseId",
    DIAMONDS = "diamonds",
    MONEY = "money",
}
